(("default"   . ((user-emacs-directory   . "~/.dotfiles/.emacs.d")))
 ("myconfig" . ((user-emacs-directory . "~/.emacs-configs/my_emacs_conf")))
 ("doom"      . ((user-emacs-directory   . "~/.emacs-configs/doom-emacs")
                 (env . (("DOOMDIR"      . "~/.dotfiles/.doom.d")))))
 ("spacemacs" . ((user-emacs-directory   . "~/.emacs-configs/spacemacs")
                 (env . (("SPACEMACSDIR" . "~/.dotfiles/.spacemacs.d")))))
 ("crafted-emacs" . ((user-emacs-directory . "~/.emacs-configs/crafted-emacs")))
 ("efs"       . ((user-emacs-directory   . "~/.emacs-configs/emacs-from-scratch"))))
