;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	c-indent-line-or-region
	indent-for-tab-command
	kill-region
	langtool-check
	org-beginning-of-line
	org-cycle
	org-delete-char
	org-end-of-line
	org-footnote-action
	org-force-self-insert
	org-insert-heading-respect-content
	org-insert-todo-heading
	org-kill-line
	org-meta-return
	org-metaleft
	org-metaright
	org-open-line
	org-ref-helm-insert-cite-link
	org-return-indent
	org-self-insert-command
	org-yank
	))

(setq mc/cmds-to-run-once
      '(
	end-of-buffer
	find-file
	kmacro-end-or-call-macro
	mouse-drag-mode-line
	mouse-select-window
	))
